---
- name: Automation LAMP Stack
  hosts: localhost
  # become: yes
  roles:
    - role: prerequisites
      tags: always
    - role: configure_lamp
      tags: always
    - role: reverse_proxy
      tags: always

 